stages:
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  tags: [docker,hliss.ru]
  only:
    - master
  script:
    - docker build --build-arg CI_PIPELINE_IID="$CI_PIPELINE_IID" --build-arg GITLAB_TOKEN="$CI_JOB_TOKEN" --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    
